# Generated by Django 2.2 on 2019-04-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odapp', '0002_auto_20190408_2027'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
