# Generated by Django 2.2 on 2019-04-09 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odapp', '0003_auto_20190409_0624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
    ]
