# Generated by Django 2.2.1 on 2019-05-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odapp', '0005_auto_20190409_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('price', models.CharField(max_length=5)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
